[package]
name = "sift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
automerge = "0.5.9"
autosurgeon = "0.8.3"
chrono = "0.4.37"
crossterm = "0.27.0"
ratatui = "0.26.2"
serde = { version = "1.0" , features = ["derive"] }
serde_json = "1.0.115"
tui-prompts = "0.3.8"
