# Use 2024 edition semantics, but will be replaced with "style_edition".  See
# https://github.com/rust-lang/rustfmt/issues/3383#issuecomment-1649048685
version = "Two"

max_width = 100

use_field_init_shorthand = true
imports_granularity = "Module"

#
# Unstable options.  This requires nightly rust to format code.  Try:
#
# 1) cargo make format
# 2) cargo +nightly fmt --all
#
# The latter requires rustup.
#

group_imports = "StdExternalCrate"
wrap_comments = true
reorder_impl_items = true
