max_width = 100

use_field_init_shorthand = true
imports_granularity = "Module"

#
# Unstable options.  This requires nightly rust to format code.  Try:
#
# 1) cargo make format
# 2) cargo +nightly fmt --all
#
# The latter requires rustup.
#

group_imports = "StdExternalCrate"
wrap_comments = true
reorder_impl_items = true
